In [27]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LinearRegression
import joblib

In [28]:
df = pd.read_csv('food_data.csv')

In [29]:
df.head()

,Dish Name,Calories (kcal),Carbohydrates (g),Protein (g),Fats (g),Free Sugar (g),Fibre (g),Sodium (mg),Calcium (mg),Iron (mg),Vitamin C (mg),Folate (µg)
0,Hot tea (Garam Chai),16.14,2.58,0.39,0.53,2.58,0.00,3.12,14.20,0.02,0.50,1.80
1,Instant coffee,23.16,3.65,0.64,0.75,3.62,0.00,4.92,20.87,0.06,1.51,5.60
2,Espreso coffee,51.54,6.62,1.75,2.14,6.53,0.00,13.98,58.10,0.15,1.51,5.53
3,Iced tea,10.34,2.70,0.03,0.01,2.70,0.00,0.23,1.18,0.02,5.95,1.28
4,Raw mango drink (Aam panna),35.92,9.05,0.16,0.03,7.49,0.61,79.82,7.08,0.14,45.30,14.05

In [30]:
df = df.rename(columns={'Dish Name': 'food_name',
                        'Calories (kcal)': 'calories',
                        'Protein (g)': 'protein',
                        'Carbohydrates (g)': 'carbs',
                        'Fats (g)': 'fats'})

In [31]:
df = df[['food_name', 'calories', 'protein', 'carbs', 'fats']]
df.head(10)

                                   food_name  calories  protein  carbs  fats
0                       Hot tea (Garam Chai)     16.14     0.39   2.58  0.53
1                             Instant coffee     23.16     0.64   3.65  0.75
2                             Espreso coffee     51.54     1.75   6.62  2.14
3                                   Iced tea     10.34     0.03   2.70  0.01
4                Raw mango drink (Aam panna)     35.92     0.16   9.05  0.03
5            Fruit Punch (with fresh juices)     36.12     0.14   9.38  0.03
6                Fruit Punch (with squashes)     23.13     0.07   5.99  0.02
7                                   Lemonade     20.80     0.03   5.48  0.01
8                                  Lem-o-gin     21.52     0.08   5.55  0.03
9  Cumin infused water (Jeere/Zeere ka pani)      9.09     0.17   1.86  0.11

In [32]:
x = df['food_name']
y = df[['calories', 'protein', 'carbs', 'fats']]

In [33]:
vectorizer = CountVectorizer()
x_vec = vectorizer.fit_transform(x)

In [34]:
model = LinearRegression()
model.fit(x_vec, y)

LinearRegression()

In [36]:
joblib.dump(model, 'model.pkl')
joblib.dump(vectorizer, 'vectorizer.pkl')

print("Model and vectorizer saved successfully.")

Model and vectorizer saved successfully.